sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null; # install google cloud sdk
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl  # install kubectl
    - gcloud auth activate-service-account --key-file service-account.json  # authenticate gcloud acct
    - gcloud config set project k8-sample-app
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials k8-sample-app-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t cruzee/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true cruzee/react-test npm run test